### ISSUE TITLE
GitLab CI/CD throws fatal error

### ISSUE THREAD

**Issue by AndKaz97** [docToolchain/ci-cd-demo#2]
when adding the example .gitlab-ci.yaml i get this error in my gitlab job. i cant figure out a solution. is this a known error?

> Using Docker executor with image rdmueller/doctoolchain:v2.0.5 ...
Pulling docker image rdmueller/doctoolchain:v2.0.5 ...
Using docker image sha256:cbf32dda984f0996d511[7](https://gitlab.maibornwolff.de/department-iss/applications/matrix/matrix-doc/-/jobs/415745#L7)041f34[8](https://gitlab.maibornwolff.de/department-iss/applications/matrix/matrix-doc/-/jobs/415745#L8)c44458b13f5c6ad2490990158301fbe1f5e6 for rdmueller/doctoolchain:v2.0.5 with digest rdmueller/doctoolchain@sha256:ca1cf5d2d7aa8e11cb735b93ec62c64e3b54fbb3a5d9013f661b352032cd6e40 ...
Preparing environment
00:01
Running on runner-egow6t1e-project-522-concurrent-0 via build-da25-01.mwea.de...
Getting source from Git repository
00:02
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/eGow6t1e/0/department-iss/applications/matrix/matrix-doc/.git/
Checking out 2975ad07 as main...
Removing hs_err_pid17.log
Removing hs_err_pid27.log
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:02
Using docker image sha256:cbf32dda984f0996d5117041f348c44458b13f5c6ad2490990158301fbe1f5e6 for rdmueller/doctoolchain:v2.0.5 with digest rdmueller/doctoolchain@sha256:ca1cf5d2d7aa8e11cb735b93ec62c64e3b54fbb3a5d9013f661b352032cd6e40 ...
$ export DTC_HEADLESS=true
$ ./dtcw generateSite
dtcw - docToolchain wrapper V0.29
docToolchain V2.0.5
docToolchain as CLI available
use cli install /home/dtcuser/docToolchain/bin/doctoolchain
Java Version #
./dtcw: line 73: ((: # < 8 : syntax error: operand expected (error token is "# < 8 ")
./dtcw: line 78: ((: # > 14 : syntax error: operand expected (error token is "# > 14 ")

> A fatal error has been detected by the Java Runtime Environment:

> SIGILL (0x4) at pc=0x00007f43cba2c8f2, pid=42, tid=64

> JRE version:  (14.0+33) (build )
Java VM: OpenJDK 64-Bit Server VM (14-ea+33, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
Problematic frame:
v  ~StubRoutines::call_stub

> Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/dtcuser/docToolchain/core.42)

> An error report file with more information is saved as:
/home/dtcuser/docToolchain/hs_err_pid42.log

> /home/dtcuser/docToolchain/bin/doctoolchain: line 45:    42 Aborted                 (core dumped) ./gradlew --project-cache-dir "$docDir"/.gradle -PdocDir="$docDir" "$@"
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1

**Comment by rdmueller** [comment]
it seems that you have a java version installed which output for `java -version` is a bit strange:

```
Java Version #
./dtcw: line 73: ((: # < 8 : syntax error: operand expected (error token is "# < 8 ")
./dtcw: line 78: ((: # > 14 : syntax error: operand expected (error token is "# > 14 ")
```

I guess I have fixed it - please re-download the wrapper and try again.

Have you also seen the gitlab example on https://gitlab.com/doctoolchain/ci-cd-demo ?
It somehow runs fine, so the question is, what is different in you project?

**Comment by AndKaz97** [comment]
the problem still exists, but with a new error:

> $ export DTC_HEADLESS=true
> $ ./dtcw generateSite
> Using headless mode since there is no (terminal) interaction possible
> dtcw - docToolchain wrapper V0.31
> docToolchain V2.0.5
> docToolchain as CLI available
> use cli install /home/dtcuser/docToolchain/bin/doctoolchain
> Java Version # JRE version:  (14
> ./dtcw: line 1[30](https://gitlab.maibornwolff.de/department-iss/repo-templates/arc42-template/-/jobs/423534#L30): ((: # JRE version:  (14 < 8 : syntax error: operand expected (error token is "# JRE version:  (14 < 8 ")
> ./dtcw: line 136: ((: # JRE version:  (14 > 14 : syntax error: operand expected (error token is "# JRE version:  (14 > 14 ")
> 

i also tried to clean initialise a project with your provided link and the errors are the same.
Is it possible that it might be with the config of our company GitLabRunners?

**Comment by rdmueller** [comment]
please try to update the `dtcw` - the new version should be able to better check the java version which should at least avoid the two errors above. After this, let's see which problem we still have

**Comment by AndKaz97** [comment]
i downloaded the new dtcw via curl and the error still persists!

> $ ./dtcw generateSite
> Using headless mode since there is no (terminal) interaction possible
> dtcw - docToolchain wrapper V0.35
> docToolchain V2.1.0
> docToolchain as CLI available
> use cli install /home/dtcuser/docToolchain/bin/doctoolchain
> Java Version # JRE version:  (14
> ./dtcw: line 2[27](https://gitlab.maibornwolff.de/department-iss/repo-templates/arc42-template/-/jobs/477211#L27): ((: # JRE version:  (14 < 8 : syntax error: operand expected (error token is "# JRE version:  (14 < 8 ")
> ./dtcw: line 233: ((: # JRE version:  (14 > 14 : syntax error: operand expected (error token is "# JRE version:  (14 > 14 ")
> 
> A fatal error has been detected by the Java Runtime Environment:
> 
>   SIGILL (0x4) at pc=0x00007fb487f858f2, pid=45, tid=67
> 
>  JRE version:  (14.0+[33](https://gitlab.maibornwolff.de/department-iss/repo-templates/arc42-template/-/jobs/477211#L33)) (build )
>  Java VM: OpenJDK 64-Bit Server VM (14-ea+33, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)

**Comment by rdmueller** [comment]
hm. this demo runs without flaws. You experience problems in a private environment.
Can you reproduce the problem in a public environment so that I can have a look at it?

**Comment by AndKaz97** [comment]
the problem got solved by adding the variable   _JAVA_OPTIONS: "-XX:UseAVX=0" to the gitlab-ci.yaml
